language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"

install:
    - npm install

script:
   - export APPLITOOLS_BATCH_ID=`echo ${TRAVIS_PULL_REQUEST_SHA:=$TRAVIS_COMMIT}`
   - npm run test:visual

