language: node_js
dist: xenial

addons:
  chrome: stable

before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

cache:
  directories:
    - "node_modules"

install:
    - npm install

node_js:
  - "stable"

script:
   - export APPLITOOLS_BATCH_ID=`echo ${TRAVIS_PULL_REQUEST_SHA:=$TRAVIS_COMMIT}`
   - npm run test:visual

