language: node_js

apt:
  packages:
    - google-chrome-stable

cache:
  directories:
    - "node_modules"

install:
    - npm install

node_js:
  - "stable"

script:
   - export APPLITOOLS_BATCH_ID=`echo ${TRAVIS_PULL_REQUEST_SHA:=$TRAVIS_COMMIT}`
   - npm run test:visual
