os: linux
language: node_js

node_js:
  - 'stable'

sudo: required

cache:
  directories:
    - node_modules

addons:
    chrome: stable

services:
  - docker

before_install:
  - docker pull selenium/standalone-chrome
  - docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome

install:
  - npm install

script:
   - export APPLITOOLS_BATCH_ID=`echo ${TRAVIS_PULL_REQUEST_SHA:=$TRAVIS_COMMIT}`
   - npm run test:visual -- --spec test/specs/visual.js
